update package.json and release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,6 +12,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          path: bluehost-blueprint
 
       - name: Setup Node.js
         uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
@@ -49,6 +51,16 @@ jobs:
           npm install @wordpress/env --save-dev
           npx wp-env start
           npx wp-env run cli wp theme activate bluehost-blueprint
+
+      - name: Check if site is up (status code 200)
+        run: |
+          http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8888)
+          if [ "$http_status" -eq 200 ]; then
+            echo "WordPress is up and running with status code 200!"
+          else
+            echo "Error: WordPress returned status code $http_status"
+            exit 1
+          fi
 
       - name: Create GitHub Pre-release
         uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
